### PR TITLE
Fix Maven Plugin Tests

### PR DESCRIPTION
**Pull request by kevinconaway**
@vorburger the maven plugin tests were not currently building for me.  This PR includes a number of fixes for the various issues that I found.

### CODE REVIEW

**Comment by vorburger** [comment]
@duttonw do you want to review this one?

**Comment by duttonw** [comment]
Very similar changes in some areas with my upgrade of maven to 3.5.x  in pull request https://github.com/vorburger/MariaDB4j/pull/175/files 

The updates to tighten up the assertions is also good :+1: 

I'll put these two changes together or build on top of this change when I have some time.

@kevinconaway , would you like to see this maven plugin updated to maven 3.5 or leave it at its current level for a little while longer?

**Comment by kevinconaway** [comment]
> would you like to see this maven plugin updated to maven 3.5 or leave it at its current level for a little while longer?

It doesn't matter to me, I am not using the plugin.  I was just trying to build the project and noticed that this module would not build.

**Comment by duttonw** [comment]
have merged this branch into https://github.com/vorburger/MariaDB4j/pull/175 and resolved conflicts.

**Comment by vorburger** [comment]
FYI #207

**Pull request closed without merging**
