### PR TITLE
Promoted Checkstyle Warnings to Errors

### PR DESCRIPTION
**Pull request by glittle1972**
Disabled MissingJavaDoc using severity ignore.
Altered RightCurly to alone_or_singleline to allow one line empty implementations.
Fixed missing doublequote in checkstyle.xml
Complied with outstanding checkstyle errors

### CODE REVIEW

**Comment by vorburger** [comment]
@glittle1972 this PR is presumably intended as Work-In-Progress, not for Review & Merge? It currrently as-is still fails to build, with 638 errors... 😈 The goal of the discussion in #264 would be a PR that fully passes the build. (Apologies if any misunderstandings.)

**Comment by glittle1972** [comment]
Understood - I'm still new to public contributions and thought I was merging just the checkstyle stuff into its own branch, which was already broken, not fixing it for master. I can keep working on it so feel free to reject or leave it open for updates.

**Comment by glittle1972** [comment]
OK. I removed the checkstyle:check goal from .travis.yml as
* it doesn't pick up the necessary configuration to use our checkstyle.xml, defaulting to sun_check, which is where the 638 errors are coming from.
* checkstyle **is** running when executing the standard package goal - each sub-project is reporting
```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (validate) @ mariaDB4j-core ---
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
```

**Comment by vorburger** [comment]
>  I can keep working on it so feel free to reject or leave it open for updates.

Just FYI the way this is often communicated is by using https://github.blog/2019-02-14-introducing-draft-pull-requests/ (i.e. a Draft PR = "here's some WIP I'm actively working on, maintainers do have a peek already if you like, but I'm marking it as Draft to signal that this isn't ready for full final review yet, from my side as the author" & undraft = this is good to go from me as author, feel free to merge when it LGTY).

Thanks for basing this off [my `bump-checkstyle` branch](https://github.com/vorburger/MariaDB4j/compare/bump-checkstyle). That was WIP and is now 14 commits behind the current master, let me try to rebase that, hopefully this PR will "automagically" pick that up and rebuild. (Just FYI an alternative workflow you could use to collaborate is to rebase this on master yourself and propose the PR to the `master` branch instead, and make this PR include both my first commits and yours on top.)

So is this still a "Draft" now or something "final" to review and merge if it LGTM? 🤣

**Comment by vorburger** [comment]
> let me try to rebase that

Done; `.travis.yml` had a conflict I manually resolved; WITHOUT that `checkstyle:check`, see below.

> hopefully this PR will "automagically" pick that up and rebuild.

Right that doesn't quite work (note to self: use Gerrit instead of GitHub PRs.... LOL), so now your work has conflicts (sorry). Are you comfortable to fetch and rebase on my latest `bump-checkstyle` and then force-push your 2 commits (maybe squash them?) to your `glittle1972:bump-checkstyle`?

> checkstyle:check goal from .travis.yml as it doesn't pick up the necessary configuration to use our checkstyle.xml

I dug a little bit into this and figured out why that is so - that WIP commit on my bump-checkstyle branch that you are building fixes this now (configuration moved out of plugin's execution phase goal).

**Comment by vorburger** [comment]
@glittle1972 FYI my 2nd force-push to rebase the underlying `bump-checkstyle` "base branch" now inclues #499; I hope that won't introduce any new CS violations?

**Comment by vorburger** [comment]
> now includes #499; I hope that won't introduce any new CS violations?

Duh, there are, of course... I think the simplest is if I do the git magic to cherry-pick your work on top of my branch (retaining attribution to your work, of course), and raise a new PR, and then merge that when I get a green build with it. Hope that's OK for you.

**Comment by vorburger** [comment]
Closing, as the work done here was merged as part of #500.

PS: @glittle1972 if you would like your commit in this projects history viewed on GitHub to link to https://github.com/glittle1972 you would want to associate the email address you used to make that commit with that GitHub profile. Currently your commit is not linked like that. (Which may be intentional, of course; this just FYI.)

**Pull request closed without merging**
