### PR TITLE
mariadb-10.4.x support for osx

### PR DESCRIPTION
**Pull request by bgalek**
Hi! @vorburger!
Nice work with MariaDB4J!

I've provided newer mariadb version and added mavenwrapper (for easier development).
What do you think? :)
 If it's ok, are you willing to release an updated version? :) 
I hope it will fix osx problem with openssl1.0 :)

### CODE REVIEW

**Comment by bgalek** [comment]
@vorburger travis build failed because of problem accessing mariadb-10.3.16, on my local machine build was ok

**Comment by bgalek** [comment]
ok, it's me again :D I've found the same topic in this issue: https://github.com/vorburger/MariaDB4j/issues/293

**Comment by bgalek** [comment]
@vorburger @yiftizur @bjornblomqvist @mseaton - is this fix ok with you? I don't mean to hurry - just to know do I need to publish my fork to maven ;)

**Comment by pawel-piecyk** [comment]
Tested, works fine on OSX 10.15.6.

**Comment by vorburger** [comment]
@bgalek I'll try to make time for review this weekend.

**Comment by bgalek** [comment]
@vorburger any changes of merge this week?:)

**Comment by bgalek** [comment]
@vorburger any chances? Please don't make me creating another fork! :)

**Comment by bgalek** [comment]
@vorburger the original issue has labels: `helpwanted` and `high` I assumed that it's important to fix this problem. Do you need any help testing or maybe do You want me to find more reviewers? Please tell me how to help resolve this pull request :)

**Comment by bgalek** [comment]
@vorburger :(

**Comment by bgalek** [comment]
@vorburger do you copy? :)

**Comment by bgalek** [comment]
@vorburger any progress?

**Comment by bgalek** [comment]
@vorburger it have been two months now, if you don't want this PR just tell me! I'll switch to something else or create a fork - anything will be better than waiting for your comment :(

**Comment by bgalek** [comment]
quote from readme:
`The original creator and current maintainer of this library (@vorburger) will gladly merge any pull request contributions with updates to the MariaDB native binaries. If you raise a change with new versions, you will be giving back to other users of the community, in exchange for being able to use this free project - that's how open-source works.`

**Comment by bjornblomqvist** [comment]
@bgalek As it looks like @vorburger has not had time to review this I would recommend that you split this pull request into to two. One for the 10.4.x support and one for the mavenwrapper.

Also would probably be a good idea to inform @vorburger on how to verify the source of the binaries.

These recommendation are things that would react positive too and hopefully so will @vorburger.

**Comment by vorburger** [comment]
@bgalek I don't accept binary contributions anymore, for security. The recent DB upgrades download them from a well known URL during the build. I would accept a PR for 10.4.x that's similarly implemented. You should be able to just re-use the existing thing, just copy/paste it is probably fine. Please do NOT change the source for already released DB versions.

BTW My apologies if the README isn't clear about that - contributions to clarify (as above) would be most welcome, from anyone.

The addition of the Maven Wrapper seems unrelated, and should be in a separate PR, yes.

**Comment by vorburger** [comment]
see #235

**Comment by vorburger** [comment]
#344 has a similar request (for 10.5, while this is for 10.4)

**Comment by bgalek** [comment]
@vorburger thx, for feedback. I support decision of not having binaries - but I could not make it work back then. Do you want me to prepare 10.5 version without using binaries?

**Comment by vorburger** [comment]
@bgalek if you need that version, then that would be great, yes. Keep #344 updated.

**Comment by bgalek** [comment]
@vorburger ok, I'll try my best!

**Comment by bgalek** [comment]
@vorburger and another thing, i don't want to have local maven (so I use mavenw) will you accept separate pr with mavenw migration?

**Comment by vorburger** [comment]
> @vorburger and another thing, i don't want to have local maven (so I use mavenw) will you accept separate pr with mavenw migration?

Absolutely, a separate PR for the Maven Wrapper would be welcome. Please include instructions on how I can verify the binary JAR that will be part of your PR... :smiling_imp:

**Comment by bgalek** [comment]
@vorburger sure :) i'll add it to gitinore, mavenw will download it every time ;)

**Comment by vorburger** [comment]
@bgalek sorry I have not had the time to maintain this project, but picked it up today.

Would you like to rebase this PR, squash your commits into 1, so that I can re-review it now?

Or are you no longer using MariaDB4j and would like this PR to be closed?

BTW re. DB JARs see also #484.

**Comment by bgalek** [comment]
@vorburger hi! We've moved back to h2, closing this old PR :)

**Pull request closed without merging**
