### PR TITLE
 Add MariaDB 10.3.7 for Linux, Windows and MacOS

### PR DESCRIPTION
**Pull request by jtmuhone**
Added MariaDB 10.3.7 for Linux, Windows and MacOS.
Also fixed compilation issues with Windows: test for datadir with space failed and maven plugin test couldn't find a proper timezone.
Linux and Windows binaries have been downloaded from official MariaDB site. MacOS binaries have been compiled from source on MacOS 11.2.6 Sierra VirtualBox machine.
PR has been tested on Ubuntu Linux 18.04.1, Window 10 VirtualBox machine, MacOS 11.2.6 VirtualBox machine, MacOs 11.3 on MacBook Pro and Windows 10 Enterprise 1803 on Lenovo T460s.

### CODE REVIEW

**Comment by vorburger** [comment]
@jtmuhone cool! Thanks a lot for your contribution. 

> Windows: test for datadir with space failed

This will be appreciated by a number of people (e.g. #58, #137, #179, #108).

I don't want to be a pain and am grateful for your contribution and willing to merge it as is, but if you had a moment to raise the Windows related fixes as a separate PR from the new 10.3.7 binary versions, I think that would be cool, as it would let people cherry-pick that separately. If you don't have time for that, no problem.

@230 raises an interesting idea about not including binaries in this Git repo anymore. I don't suppose you would have any interest in working together with @srbala to do it like that here?

**Comment by qinghui-xu** [comment]
Thx!

**Comment by srbala** [comment]
@jtmuhone I have tried your changes in local fails on `mvn clean package`. Initially tried you changes in to a separate branch https://github.com/srbala/MariaDB4j/commits/pr-229 and even tried direct clone from your repository https://github.com/jtmuhone/MariaDB4j both attempts failed

`[INFO] mariaDB4j (all-in-one artifact) .................... FAILURE [  0.731 s]`
`[ERROR] Failed to execute goal on project mariaDB4j: Could not resolve dependencies for project ch.vorburger.mariaDB4j:mariaDB4j:jar:2.4.1-SNAPSHOT: The following artifacts could not be resolved: ch.vorburger.mariaDB4j:mariaDB4j-db-linux64:jar:10.3.7, ch.vorburger.mariaDB4j:mariaDB4j-db-win32:jar:10.3.7, ch.vorburger.mariaDB4j:mariaDB4j-db-mac64:jar:10.3.7: Could not find artifact ch.vorburger.mariaDB4j:mariaDB4j-db-linux64:jar:10.3.7 in central` 

`
[build.log](https://github.com/vorburger/MariaDB4j/files/2948920/build.log)
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
`

**Comment by vorburger** [comment]
The DBs are not installed by "mvn install" (intentionally, because they are
versioned separately, see README), so just do e.g. "mvn -f DBs/pom.xml
clean install" first...

Once we agree to merge this, I'll deploy the new DB to Maven central and
this isn't required anymore.

Are either of you interested in reworking this to DL instead of having the
binaries in git, or would you both like to see this go in as is? Does
anyone else reading this have any views re this, and is perhaps willing to
help implement a DL and unpack in POM?

**Comment by srbala** [comment]
@vorburger Thanks for tip. Now I am able to package it. Good to go.

I have started working to implement DL and unpack, I'll send you a PR soon

**Comment by jtmuhone** [comment]
I made a rebase on top of upstream/master and a force push.

**Comment by vorburger** [comment]
> I made a rebase on top of upstream/master and a force push.

@jtmuhone I'll merge the Windows related fixes ASAP, watch #234; again, a very big Thank You!

Re. the new MariaDB 10.3.7 binaries, hope you're OK if we wait to first see #230.

**Comment by srbala** [comment]
@jtmuhone my changes are in https://github.com/srbala/MariaDB4j/tree/feat-231 related to #230, typo in branch name.

**Comment by srbala** [comment]
@jtmuhone created new PR #235, can replace this PR, please review

**Comment by vorburger** [comment]
@jtmuhone with #235 finally merged (again, really sorry for the long delay), do you want to close this one now? Or were there things in the PR which you think still would have value to apply now? Specifically, I noticed only now that you had included some [changes to DB.java which appear to be related to Windows support](https://github.com/vorburger/MariaDB4j/pull/229/files?file-filters%5B%5D=.java#diff-452b8e4bb6ec82a375b2ce5bbea9eb97), and not directly to the rest of this PR, which perhaps would still be valuable to raise as a separate new PR - would you be willing to contribute that? Perhaps that will actually help for #137 / #58 / #179 ... ?

**Comment by vorburger** [comment]
> you had included some [changes to DB.java which appear to be related to Windows support](https://github.com/vorburger/MariaDB4j/pull/229/files?file-filters%5B%5D=.java#diff-452b8e4bb6ec82a375b2ce5bbea9eb97), and not directly to the rest of this PR, which perhaps would still be valuable to raise as a separate new PR - would you be willing to contribute that? Perhaps that will actually help for #137 / #58 / #179 ... ?

I totally forgot that change was already earlier in #234.

From my side, I therefore think this PR can/should be closed - no objection from you @jtmuhone?

Again, thanks a lot for contributing! Hope this isn't discouraging. New PRs are very very welcome!

**Pull request closed without merging**
