### PR TITLE
Issue #63 - Provide a callback if the DB process crashes

### PR DESCRIPTION
**Pull request by neeleshs**
Sorry for the delay on this. Got distracted with work

### CODE REVIEW

**Comment by vorburger** [comment]
@neeleshs thanks! This has some merge conflicts, do you know how to use git rebase to resolve this?

**Comment by neeleshs** [comment]
Yes, my bad. I'll get to it this week. Thanks!

**Comment by vorburger** [comment]
@neeleshs I'm about to release 2.3.0 (#106) and unless you, or anyone else reading this, want to do what we discuss above ASAP I don't think this will make it into that release...

**Comment by duttonw** [comment]
I'm happy to fix up the merge conflicts to get this merged in if still required.

**Comment by vorburger** [comment]
@duttonw sure, go for it! @neeleshs seems to have lost interest in this, so I just left it, but I would certainly be happy re-review and merge this, if it has value for other users in the MariaDB4j user community who are willing to step to finish this! 

Just be aware that things have moved around since this was raised - the ManagedProcess & Co. is now no longer in this repo but [over here in ch.vorburger.exec](https://github.com/vorburger/ch.vorburger.exec/blob/master/src/main/java/ch/vorburger/exec/.java). That's not a big problem, of course - just first raise a PR there, I'll review, merge, release that, then you can update this PR including a bump of ch.vorburger.exec with that. Sounds like a plan?

**Comment by duttonw** [comment]
This pull request has been split into the following:
https://github.com/vorburger/ch.vorburger.exec/pull/5
https://github.com/vorburger/MariaDB4j/pull/144

**Pull request closed without merging**
