### PR TITLE
clean up mariaDB4j-app POM

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@kbyyd24 (and @duttonw) OK for you?

**Comment by vorburger** [comment]
BTW it (mariadb-java-client) just got bumped in #158, and with this change we have the version only in 1 place.

**Comment by duttonw** [comment]
If it compiles, yep 👍

**Comment by kbyyd24** [comment]
Yeah, that's OK

**Pull request merged**
