### PR TITLE
Removing `--tmpdir` argument from `mysql_install_db` as it's used in `mysqld`

### PR DESCRIPTION
**Pull request by MazenAmria**
Resolving https://github.com/vorburger/MariaDB4j/issues/632 and https://github.com/vorburger/MariaDB4j/issues/634

### CODE REVIEW

**Comment by vorburger** [comment]
> Resolving #632 and #634

That would #632 and #646 (#634 was just a dependabot)...

... I will test this by creating a PR which combines this with #638!

@MazenAmria Thank you for your further investigation of this issue, and for having raised this PR.

**Comment by vorburger** [comment]
@MazenAmria given that #649 failed, I am (have to be) reluctant to accept and merge this as-is - hope that makes sense?

Would you be interesting in contributing further and help figure out what's going on? /Cc @jejanim

PS: To be clear, I AM very happy to merge this IFF I can "verify" that it fully fixes #632 "via" #638.

**Comment by MazenAmria** [comment]
@vorburger yeah that's totally fine
btw, I'm looking into the problem right now, and I'll be happy to help.

**Review by TareqK — APPROVED** [review]

**Comment by TareqK** [comment]
Dying because of this as well

**Comment by vorburger** [comment]
Sorry for the long silence on this. I've fixed a number of others things in this project today, and am hoping to find time another weekend to upgrade the project overall from Java 11 to Java 17 and then be able to pick this PR up....

PS: If you use MariaDB4j professionally, please consider either taking a [Tidelift subscription](https://tidelift.com) or [GitHub Sponsor](https://github.com/sponsors/vorburger) to support future maintenance!

**Comment by vorburger** [comment]
@MazenAmria I have FINALLY (just now) merged your work here as part of #649 as https://github.com/vorburger/MariaDB4j/pull/649/commits/60d1d628ffb7c37dbd4bfe11d734a5a55616dd75 (with you still credited as the Author of it).! FYI @TareqK. Therefore closing this PR now. Many many thanks again for this contribution!

**Pull request closed without merging**
